export const metadata = {
  title: 'Portifolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className="dardk-theme">{children}</body>
    </html>
  )
}