import AOSInitializer from './AOSinitializer'; // Ajuste o caminho conforme necessário

export const metadata = {
  title: 'Portifolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head>
      </head>
      <body className="dardk-theme">
        <AOSInitializer />
        {children}
      </body>
    </html>
  )
}
